### ISSUE TITLE
Bug: log output in stdout is not line buffered when using `forkThread`

### ISSUE THREAD

**Issue by jack-davies** [aesiniath/unbeliever#103]
I have a program with the following structure.

```haskell
program :: Program None ()
program = do
    threadA <- forkThread poll
    threadB <- forkThread poll
    mapM_ waitThread_ [threadA, threadB]

poll :: Program None ()
poll = forever $ do
    sleepThread 1
    writeS "Hello"
```

The expected behaviour is that each thread will output `Hello` to the console once per second. Instead after a long delay a huge chunk of output is written to the console, consistent with output not being line buffered.

The correct behaviour is observed with line buffering explicitly set:

```diff
program :: Program None ()
program = do
+++ liftIO $ hSetBuffering stdout LineBuffering
...
```

**Comment by istathar** [comment]
This is very strange, since the default output buffering is supposed to be Line and `write` outputs a `\n`.

Possibly something about the threads changes the behaviour, but, er...

**Comment by istathar** [comment]
@jack-davies I hate to say this, but your code runs fine here. :/

I absolutely believe your report so we have a deeper issue. Maybe we should try `hGetBuffering` on your machine to see if it's somehow defaulting to something different. 

[I'm happy to have `execute` explicitly set buffering if it's needed! but it really shouldn't have been. So something else is going on here]

**Comment by istathar** [comment]
@jack-davies have you seen this recently?
