### ISSUE TITLE
String escaping when encoding to JSON is insufficient

### ISSUE THREAD

**Issue by istathar** [aesiniath/unbeliever#111]
Looks like we've done escaping of strings when encoding to JSON wrong. Right now the `escapeString` function in Core.Encoding.Json only escapes `"` and doesn't escape `\`.

https://github.com/aesiniath/unbeliever/blob/faa1c9ca4c8634b17de5011d47d7c80207e5c36f/core-data/lib/Core/Encoding/Json.hs#L183-L186

With the result that this program

```
    encodeString "This is a \"test\""
```

didn't result in a valid JSON string because the interior quotes got escaped but the backslashes didn't.

According to [this](https://stackoverflow.com/a/3020108/901918) post,

> Escape it according to the RFC. JSON is pretty liberal: The only characters you must escape are `\\`, `"`, and control codes (anything less than U+0020).

at this point I'm not even worried about control codes, but we really do need to escape backslashes.

**Comment by jack-davies** [comment]
Out of interest, the approach taken by **aeson** is at https://github.com/haskell/aeson/blob/master/src/Data/Aeson/Text.hs#L77-L96

**Comment by istathar** [comment]
@jack-davies yeah, their algorithm makes sense too. The algorithm that's here breaks the Rope into pieces if quotes (and now, if backslashes) are found, and inserts the appropriate escape character, rather than building up an entirely new text object character by character.

**Comment by istathar** [comment]
I just got bitten by a `TAB` needing escaping. ffs

@jack-davies you are right. I need to rebuild the escape the output character by character, or else split more aggressively.

**Comment by istathar** [comment]
This is fixed properly now.
