### ISSUE TITLE
Outdated reference to utf16 `Data.Text` in docs

### ISSUE THREAD

**Issue by sullyj3** [aesiniath/unbeliever#119]
https://github.com/aesiniath/unbeliever/blob/c358dd2cf4651ba6b25f4c0b6c55fe8a4fe85c19/core-text/lib/Core/Text/Rope.hs#L42-L46

I believe this is out of date as of https://github.com/haskell/text/pull/365

**Comment by istathar** [comment]
Yeah, I've been waiting for **text** 2.0 to propagate. Once people are more widely able to use GHC 9.0 and `lts-19.x` and we're able to remove the conversion step that'll be great. You're right, though, this comment is now dated.
