### ISSUE TITLE
forkThreads should inherit parent thread's telemetry Datum

### ISSUE THREAD

**Issue by istathar** [aesiniath/unbeliever#200]
When you use `forkThread` the new thread doesn't continue to modify the parents' span (specifically, you get a fork of the Datum which forks the map that holds the telemetry key/value pairs, so subsequent changes to the telemetry are local to the new thread). This may not have been the right design choice.

The example we've run into is that if you use `timeoutThread` to wrap a timeout around a subprogram any telemetry you add in the subprogram is _lost_. That's because `timeoutThread` internally uses `raceThreads` and that uses `forkThread` and thus the above machinery which forks the Datum. But this isn't what you expect:

```haskell
    encloseSpan "worker" $ do
        timeoutThread 10 $ do
            ...
            telemetry
                [ metric "counter" 42
                ]
            ...
```
in this example, the telemetry for the `"worker"` span will NOT include a value for `"counter"`. That seems wrong.

I've looked through the code bases I have access to, and uses of `forkThread` tend to either be for brief little side tasks inside larger spans (in which case any telemetry belongs to the span that's in progress), or are launching off entirely new programs which will pretty much immediately call `encloseSpan` or even `beginTrace` and have its own identity in the telemetry.

So I think the maxim that we've had elsewhere in this codebase of "want a new span? call encloseSpan!" should hold here too, and `forkThread` should not be special about telemetry.

**Comment by justinlynn** [comment]
hmm - right now I don't believe I'm depending on that metadata position on spans, but I can't speak for anyone else - we'd need to review dashboards for the uses we have. It'd be good to put out a compatibility notice in case any users rely on that behaviour. At some point - it'd be good to discuss some kind of versioning for span metadata/parent metadata relationships/placement (or something) as a separate best practice for users of the library ... but I haven't got any great ideas for it right now. It feels weird to not have some sort of trace schema or something... but it's not like honeycomb has the notion of that.

**Comment by justinlynn** [comment]
Now that I think about it - you're going to have to synchronise access to the Datum now across threads... that might get tricky and/or you're going to need to define write conflict behaviour for metadata/etc... or you could get some really weird trace results.
