### ISSUE TITLE
Better Unicode support

### ISSUE THREAD

**Issue by luke-clifton** [aesiniath/unbeliever#34]
Would be great if the text type had some good unicode support. Especially for things like iterating over grapheme clusters.

**Comment by afcowie** [comment]
@luke-clifton Luke you were working on an innovative text handling subsystem a while back. Did you ever make any headway on that idea?

**Comment by istathar** [comment]
I just came across http://hackage.haskell.org/package/unicode-tricks which seems to have some interesting ideas about supporting more complicated Unicode characters. In particular the `toUnicodeText` / `fromUnicodeText` design of UnicodeText seems to be similar to the interoperability approach taken in this library.
