### ISSUE TITLE
add `Num a => Rope -> Maybe a`

### ISSUE THREAD

**Issue by dmvianna** [aesiniath/unbeliever#82]
A very common scenario is that we want to pass a parameter to a CLI that is to be interpreted as an integer or a float. Currently `Core.Text` does not easily handle that situation.

**Comment by istathar** [comment]
I think there are two issues here. 

1. Converting numbers (in various forms) to Rope.
2. Handling numeric command-line option values. 

It's possible a good solution to 1 might make 2 trivial but we also might want a dedicated helper `query*` function in **core-program** if it's at all finicky.

Anyway, 1 first. What does a good `convertInteger` look like?

**Comment by carlosdagos** [comment]
Would a Read instance help here? You would not have the Num restriction but there is a 'readMaybe' that (mostly) matches the type signature you want: https://hackage.haskell.org/package/base-4.16.1.0/docs/Text-Read.html#v:readMaybe

The downside could be that having a Read instance opens up the possibility for the use of unsafe functions such as the simple 'read'

**Comment by istathar** [comment]
@carlosdagos you're right, a Read instance could be a good idea, but it's String -> Rope. We've kinda already got that, in Textual. Which perhaps suggests the solution: an instance of Textual for Int, Float etc. 

```
λ> execute (write (intoRope 17))
17
λ>
```

which would presumably go through Show which is inefficient, but whatever; most numerical conversions to text strings do go via Show -> String. And meanwhile we've got `writeS` and `debugS` which do exactly that. Is what it is.

There'd be no particularly valid `fromRope` implementation; so at best the Textual instance would be partial, and we don't like to do that to people, but perhaps it's ok. Or we return `""` on an invalid conversion back.

**Comment by istathar** [comment]
I've been thinking along the lines of creating another conversion typeclass. Rather than Textual Int (which really doesn't have a valid fromRope) perhaps 

```
class Numeric x where
    parseNumber :: Rope -> Maybe x
```

Most conversion functions around the ecosystem are Maybe whatever, and most types have one way or another to parse text, so this might be a nice way to wrap those up in one place.

**Comment by istathar** [comment]
The design I'm heading toward is

```
    thing <-
        queryOptionValue "thing" >>= \case
            Nothing -> throw Boom
            Just value -> case parseExternal value of
                Nothing -> throw Boom
                Just value' -> pure value'
```

that's still very cumbersome.

**Comment by istathar** [comment]
How about this:

```haskell
    thing2 <-
        queryOptionValue "thing" >>= parseOptionValue
```

with:

```haskell
parseOptionValue :: Externalize x => Maybe Rope -> Program z x
```

**Comment by istathar** [comment]
Better idea:

```haskell
    thing3 <-
        queryOptionValue' "thing" >>= \case
            ...
```

```haskell
queryOptionValue' :: Externalize x => LongName -> Program z (Maybe x)
```

this allows us to just assume success and throw an appropriate exception if not, which is actually what goes on elsewhere in the command-line parameter handing subsystem.
