### ISSUE TITLE
Textual instance for LogStr

### ISSUE THREAD

**Issue by carlosdagos** [aesiniath/unbeliever#89]
The packages `wai-extra`, which implements the `Middleware` interface for `wai` depends on `fast-logger`: https://hackage.haskell.org/package/wai-extra

The `fast-logger` package defines a `LogStr`: https://hackage.haskell.org/package/fast-logger-3.1.0/docs/System-Log-FastLogger.html#t:LogStr

I find a couple of interesting things here:

1. There is a very strong similarity between `LogStr` and `Rope`:

   ```haskell
   data LogStr = LogStr !Int Builder
   ```

   And

   ```haskell
   newtype Rope = Rope (F.FingerTree Width S.ShortText)
   ```

1. It's interesting that both data types have good performance for append operations.

With that said:

If we could have a `Textual` instance `LogStr`, it would help towards a potential implementation of a `Middleware` for `wai` 😄 

Downside: More dependencies in `core-text`.

**Comment by Cmdv** [comment]
@carlosdagos ahh I see so instead of having a whole wai app wrapped in `Program` it would become a `Middleware`?
Would you still get the same access to its instance/functions through the `ReaderT` inside the handlers?

**Comment by carlosdagos** [comment]
I think using `Middleware` (which is nothing but a type alias for `Application -> Application` is a good way to keep things nicely decoupled, potentially as a separate lib like `core-wai` or something (?). However, I'm still thinking about it and probably would need to experiment a bit to see all the pros and cons

**Comment by istathar** [comment]
@carlosdagos I've adapted as your idea and integrated it directly into the Program monad as #90. If we use that I think it supersedes this? I tried messing around with the logging helers in **wai-extra**; Vince's examples really helped me understand what was going on there but probably if we launch the webserver directly with an appropriately coonfigured Middleware it looks like it works.

**Comment by Cmdv** [comment]
@carlosdagos @istathar Think my main con would be finding information/ blog post / examples of solving problems when one wants to use servant & wai. With the method in the PR we'd be wrapping it inside of `core` which feels like an extra level of abstraction. Rather than a middleware that runs along side of the application and handles a piece ie "logging".

The primary problem being the type of `Program` having the static Monad set to `IO`. Which I've previously shown and discussed how that doesn't align with the whole implementation in wai and servant.

Personally I would have used something like [this code](https://github.com/EarnestResearch/honeycomb-wai-haskell/blob/master/src/Network/Wai/Honeycomb.hs#L48-L123) to be a middleware if the end goal was to send logs to honeycomb. 

I seem to be really missing the benefits of using `unbeliever` as part of a web server and would love to be shown the pros of it so I can have pros + cons ?
 
As a terminal tool yes it's really good but still unsure the functionality it provides is also suited for servers. Are we trying to fit a square peg into a round hole for the sake of being able to use `unbeliever` ?

**Comment by carlosdagos** [comment]
> Think my main con would be finding information/ blog post / examples of solving problems when one wants to use servant & wai

The code in #90 doesn't really touch on `servant`, it does two things primarily:

1. Creates a `launchWebserver` action on the `Program` monad that works with any `wai` `Application`. How one gets this `Application` is up to the consumer, [this is commented here](https://github.com/aesiniath/unbeliever/blob/8958901e8910fca74d876138a3e4264b81959782/core-webserver-warp/lib/Core/Webserver/Warp.hs#L44-L46).
2. Creates a `loggingMiddleware :: Context τ -> Middleware`. This is used within `launchWebserver`, the implementation details of that are not necessarily important for this issue, I don't think.

> The primary problem being the type of Program having the static Monad set to IO. Which I've previously shown and discussed how that doesn't align with the whole implementation in wai and servant.

If your concern is using blogposts+examples then yes I agree, using `Program` within Servant `Handler`s is not too straightforward. But I don't believe that `Program` setting its internal monad to `IO` is indeed the problem. If we want to use `honeycomb-haskell` as an example, they also provide a [`servant`+`rio` integration](https://github.com/EarnestResearch/honeycomb-haskell/blob/master/honeycomb-servant-server-rio/src/Servant/Server/Honeycomb/RIO.hs) and well, it does pretty much the same things as #90 to be honest, except with different constructs and a different set of ecosystem libraries. 

> Personally I would have used something like this code to be a middleware if the end goal was to send logs to honeycomb.

That code is 2-3 years old with no updates. I think you meant [this code here](https://github.com/EarnestResearch/honeycomb-haskell/blob/master/honeycomb-wai/src/Network/Wai/Honeycomb.hs). I don't have any issues with that code at all. As said above though, I think it mostly does the same thing as #90 

> I seem to be really missing the benefits of using unbeliever as part of a web server and would love to be shown the pros of it so I can have pros + cons ?
>
> As a terminal tool yes it's really good but still unsure the functionality it provides is also suited for servers. Are we trying to fit a square peg into a round hole for the sake of being able to use unbeliever?

`unbeliever` is a set of opinionated libraries. The docs do a pretty good job of explaining those opinions: https://hackage.haskell.org/package/core-program-0.4.2.0/docs/Core-Program-Execute.html

I don't think that the demarcation between console and webserver is all too important here if I'm honest. The webserver is `warp` and that's still used, just that it's launched via the `Program` monad with `liftIO`, so that it can play along with `execute` and therefore unify all the administrative tasks that `core-program` aims to solve in a unified way 😄 

With all that said, I think that this issue is no longer relevant as #90 covers the logging bits for an `Application`.

**Comment by Cmdv** [comment]
@carlosdagos ah thanks that explains a lot. Guess we need a chat about _"the administrative tasks that core-program aims to solve"_ for me to understand all the benefits it brings.

Think my scepticism is routed from having to have a buy in to what could be classed as an eco system in `unbeliever`. Much like the choice of using servant/wai but this is a level above that. This isn't necessarily  a bad thing but I foresee issues potentially arising that require complexity that might not have been needed if things had just been vanilla. 🤔
