### ISSUE TITLE
`info` not working with Servant/Warp

### ISSUE THREAD

**Issue by Cmdv** [aesiniath/unbeliever#95]
There seems to be a slight issue with `info` in the example bellow, `write` + `print` display to the terminal but `info` does not.

```Haskell
fetchSomething :: Program Settings [Something]
fetchSomething = do
    write "test1"
    info "test2"
    _ <- liftIO $ print "test3"
    ...
```
result of calling that endpoint/handler is:

```
test1
"test3"
```

**Comment by istathar** [comment]
When I was testing this I either did

```
$ stack run snippet -- --verbose
```
or
```
program = do
    setVerbosityLevel Verbose
    ...
```
did you set `--verbose` or `--debug` level when running it? If not, would explain where your informational level message went.

**Comment by Cmdv** [comment]
ah yeah this worked fine thanks :) Will close 🎉
