### ISSUE TITLE
Adapt W3C Trace Context recommendation

### ISSUE THREAD

**Issue by istathar** [aesiniath/unbeliever#96]
As advised by @lizthegrey, we should switch the generated trace identifiers and span identifiers to the format recommended by the [W3C Trace Context Specification][1]. 

The benefit of doing this is that should we have to pass a trace-id / span-id-as-parent to a child system that we don't control but which is supporting the OpenTelemetry and/or W3C standardard they're more likely to be happy if we pass them identifiers in this format. Likewise we should be prepared to accept incoming traces in this format (ie with `usingTrace`) that someone else initiated further out before getting to our code. Might as well get used to this format.

Specifically the change is,

- **trace** is to be a "16-byte array, for example, `4bf92f3577b34da6a3ce929d0e0e4736`"[^2], ie 32 characters of lower case hexidecimal, and 
- **span** is to be an "8-byte array, for example, `00f067aa0ba902b7`"[^3], ie 16 characters of lower case hexidecimal.

All zeros invalid.

These identifiers still have to be unique within the dataset. A UUID with the hyphens removed is what they do upstream; for traces we can presumably keep our generator but just stop converting to base 62.

For spans I'm not so sure. Question: if spans have to be unique [in Honeycomb] then not having the second half of the UUID (the MAC address) seems like it increases the likelihood of collision. I realize most of the time we just {shrug} about that sort of thing but I'm a bit surprised span IDs aren't 16 bytes, too.

[1]: https://www.w3.org/TR/trace-context/#traceparent-header
[^2]: https://www.w3.org/TR/trace-context/#trace-id
[^3]: https://www.w3.org/TR/trace-context/#parent-id

**Comment by lizthegrey** [comment]
spans must be unique per-trace, not globally.
